name: hive_todo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  animate_do: ^3.3.4
  cupertino_icons: ^1.0.8
  flutter_cupertino_date_picker_fork: ^1.0.7
  flutter_slider_drawer: ^3.0.2
  ftoast: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  lottie: ^3.2.0
  panara_dialogs: ^0.1.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/lottie/